# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, max_length=150, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=150, null=True, verbose_name='年龄')),
                ('ethnic', models.CharField(blank=True, max_length=150, null=True, verbose_name='民族')),
                ('political_role', models.CharField(blank=True, max_length=150, null=True, verbose_name='政治面貌')),
                ('native_place', models.CharField(blank=True, max_length=150, null=True, verbose_name='籍贯')),
                ('health', models.CharField(blank=True, max_length=150, null=True, verbose_name='身体状况')),
                ('PID', models.CharField(blank=True, max_length=150, null=True, verbose_name='身份证号')),
                ('marital_status', models.CharField(blank=True, max_length=150, null=True, verbose_name='婚姻状况')),
                ('graduate_institutions', models.CharField(blank=True, max_length=150, null=True, verbose_name='毕业院校')),
                ('education_background', models.CharField(blank=True, max_length=150, null=True, verbose_name='学历')),
                ('major', models.CharField(blank=True, max_length=150, null=True, verbose_name='专业')),
                ('timeofwork', models.CharField(blank=True, max_length=150, null=True, verbose_name='参加工作时间')),
                ('wished_salary', models.CharField(blank=True, max_length=150, null=True, verbose_name='希望薪金/月')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='联系方式')),
                ('addr', models.CharField(blank=True, max_length=150, null=True, verbose_name='家庭住址')),
            ],
        ),
    ]
