# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171201_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-01 08:34:59', max_length=40, verbose_name='创建时间'),
        ),
    ]
